# Generated by Django 4.2.11 on 2026-04-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.CharField(max_length=200)),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('anchor_url', models.CharField(max_length=200)),
                ('movie_genre', models.CharField(max_length=10)),
                ('movie_title', models.CharField(max_length=20)),
                ('lower_rating', models.CharField(max_length=5)),
                ('upper_rating', models.CharField(max_length=5)),
            ],
        ),
    ]
