# Generated by Django 4.2.11 on 2026-04-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('img_src', models.CharField(max_length=200)),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_url', models.CharField(max_length=200)),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
                ('celebrity_url', models.CharField(max_length=200)),
                ('celebrity_name', models.CharField(max_length=50)),
                ('celebrity_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('anchor_class', models.CharField(max_length=2)),
                ('icon_class', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_URL', models.CharField(max_length=200)),
            ],
        ),
    ]
