# Generated by Django 4.2.11 on 2026-04-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_advertisement_celebrity_sociallink_trailer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebrity',
            options={'verbose_name_plural': 'Celebrities'},
        ),
    ]
