# Generated by Django 5.2 on 2026-05-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_movietheater_movietv_news_traileritem_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='contant',
            new_name='content',
        ),
    ]
